pipeline:
  name: flow-build-test
  identifier: flowbuildtest
  projectIdentifier: NgLabs
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: ounit_test_linux
        identifier: ounit_test_linux
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Create cache breaker
                  identifier: Create_cache_breaker
                  spec:
                    connectorRef: harnessdocker
                    image: flowtype/flow-ci:linux-x86_64
                    shell: Sh
                    command: |
                      .circleci/make_opam_cachebreaker.sh > .circleci/opamcachebreaker
                    envVariables:
                      TERM: dumb
                      OPAMYES: "true"
              - step:
                  type: Run
                  name: Init opam
                  identifier: Init_opam
                  spec:
                    connectorRef: harnessdocker
                    image: flowtype/flow-ci:linux-x86_64
                    shell: Sh
                    command: |
                      .circleci/opam_init.sh
                    envVariables:
                      TERM: dumb
                      OPAMYES: "true"
                  when:
                    stageStatus: All
                  failureStrategies: []
              - step:
                  type: Run
                  name: install deps from opam
                  identifier: install_deps_from_opam
                  spec:
                    connectorRef: harnessdocker
                    image: flowtype/flow-ci:linux-x86_64
                    shell: Sh
                    command: |-
                      #!/bin/bash -eo pipefail
                      .circleci/opam_init.sh
                      make deps
                    envVariables:
                      TERM: dumb
                      OPAMYES: "true"
                  when:
                    stageStatus: All
                  failureStrategies: []
              - step:
                  type: Run
                  name: Install extra deps from opam
                  identifier: Install_extra_deps_from_opam
                  spec:
                    connectorRef: harnessdocker
                    image: flowtype/flow-ci:linux-x86_64
                    shell: Sh
                    command: |-
                      #!/bin/bash -eo pipefail
                      .circleci/opam_init.sh
                      opam install ounit2.2.2.4 | cat
                    envVariables:
                      TERM: dumb
                      OPAMYES: "true"
                  when:
                    stageStatus: All
                  failureStrategies: []
              - step:
                  type: Run
                  name: Run tests
                  identifier: Run_tests
                  spec:
                    connectorRef: harnessdocker
                    image: flowtype/flow-ci:linux-x86_64
                    shell: Sh
                    command: |-
                      #!/bin/bash -eo pipefail
                      .circleci/opam_init.sh
                      opam exec -- make ounit-tests-ci
                    envVariables:
                      TERM: dumb
                      OPAMYES: "true"
                  when:
                    stageStatus: All
                  failureStrategies: []
  properties:
    ci:
      codebase:
        connectorRef: gitconnectordhruba
        repoName: flow
        build: <+input>
