pipeline:
  name: flow-build-test
  identifier: flowbuildtest
  projectIdentifier: NgLabs
  orgIdentifier: default
  tags: {}
  stages:
    - parallel:
        - stage:
            name: ounit_test_linux
            identifier: ounit_test_linux
            type: CI
            spec:
              cloneCodebase: true
              platform:
                os: Linux
                arch: Amd64
              runtime:
                type: Cloud
                spec: {}
              execution:
                steps:
                  - step:
                      type: Run
                      name: Create cache breaker
                      identifier: Create_cache_breaker
                      spec:
                        connectorRef: harnessnew
                        image: flowtype/flow-ci:linux-x86_64
                        shell: Sh
                        command: |
                          .circleci/make_opam_cachebreaker.sh > .circleci/opamcachebreaker
                        envVariables:
                          TERM: dumb
                          OPAMYES: "true"
                      when:
                        stageStatus: All
                      failureStrategies: []
                  - step:
                      type: Run
                      name: Init opam
                      identifier: Init_opam
                      spec:
                        connectorRef: harnessdocker
                        image: flowtype/flow-ci:linux-x86_64
                        shell: Sh
                        command: |-
                          if [ ! -f ~/.opam/from_cache ]; then
                            rm -rf ~/.opam
                            opam init --bare --disable-sandboxing --no-setup --yes
                          fi

                          ls
                        envVariables:
                          TERM: dumb
                          OPAMYES: "true"
                      when:
                        stageStatus: All
                      failureStrategies: []
                  - step:
                      type: Run
                      name: install deps from opam
                      identifier: install_deps_from_opam
                      spec:
                        connectorRef: harnessdocker
                        image: flowtype/flow-ci:linux-x86_64
                        shell: Sh
                        command: make deps
                        envVariables:
                          TERM: dumb
                          OPAMYES: "true"
                      when:
                        stageStatus: All
                      failureStrategies: []
                  - step:
                      type: Run
                      name: Install extra deps from opam
                      identifier: Install_extra_deps_from_opam
                      spec:
                        connectorRef: harnessdocker
                        image: flowtype/flow-ci:linux-x86_64
                        shell: Sh
                        command: |
                          #!/bin/bash -eo pipefail
                          .circleci/opam_init.sh
                          opam install ounit2.2.2.4 | cat
                        envVariables:
                          TERM: dumb
                          OPAMYES: "true"
                      when:
                        stageStatus: All
                      failureStrategies: []
                  - step:
                      type: Run
                      name: Run tests
                      identifier: Run_tests
                      spec:
                        connectorRef: harnessdocker
                        image: flowtype/flow-ci:linux-x86_64
                        shell: Sh
                        command: |-
                          #!/bin/bash -eo pipefail
                          .circleci/opam_init.sh
                          opam switch
                          opam exec -- make ounit-tests-ci
                        envVariables:
                          TERM: dumb
                          OPAMYES: "true"
                      when:
                        stageStatus: All
                      failureStrategies: []
              sharedPaths:
                - /flow/
        - stage:
            name: build_linux_arm64
            identifier: build_linux_arm64
            type: CI
            spec:
              cloneCodebase: true
              platform:
                os: Linux
                arch: Arm64
              runtime:
                type: Cloud
                spec: {}
              execution:
                steps:
                  - step:
                      type: Run
                      name: Start Docker image
                      identifier: Start_Docker_image
                      spec:
                        connectorRef: harnessnew
                        image: flowtype/flow-ci:linux-arm64
                        shell: Sh
                        command: echo "flowtype/flow-ci:linux-arm6 pull successfull"
                        envVariables:
                          TERM: dumb
                          OPAMYES: "true"
                  - step:
                      type: Run
                      name: Create cache breaker
                      identifier: Create_cache_breaker
                      spec:
                        shell: Sh
                        command: |-
                          make print-switch
                          make print-jsoo-version
                          opam --version
                          gcc -dumpfullversion -dumpversion
                          cat flowtype.opam
                          cat flow_parser.opam
                        envVariables:
                          TERM: dumb
                          OPAMYES: "true"
                      when:
                        stageStatus: All
                      failureStrategies: []
                  - step:
                      type: Run
                      name: Init opam
                      identifier: Init_opam
                      spec:
                        connectorRef: harnessdocker
                        image: flowtype/flow-ci:linux-x86_64
                        shell: Sh
                        command: |-
                          if [ ! -f ~/.opam/from_cache ]; then
                            rm -rf ~/.opam
                            opam init --bare --disable-sandboxing --no-setup --yes
                          fi

                          ls
                        envVariables:
                          TERM: dumb
                          OPAMYES: "true"
                      when:
                        stageStatus: All
                      failureStrategies: []
                  - step:
                      type: Run
                      name: install deps from opam
                      identifier: install_deps_from_opam
                      spec:
                        connectorRef: harnessdocker
                        image: flowtype/flow-ci:linux-x86_64
                        shell: Sh
                        command: |-
                          if [ ! -f ~/.opam/from_cache ]; then
                            rm -rf ~/.opam
                            opam init --bare --disable-sandboxing --no-setup --yes
                          fi

                          make deps
                        envVariables:
                          TERM: dumb
                          OPAMYES: "true"
                      when:
                        stageStatus: All
                      failureStrategies: []
                  - step:
                      type: Run
                      name: Install extra deps from opam
                      identifier: Install_extra_deps_from_opam
                      spec:
                        connectorRef: harnessdocker
                        image: flowtype/flow-ci:linux-x86_64
                        shell: Sh
                        command: |
                          #!/bin/bash -eo pipefail
                          .circleci/opam_init.sh
                          opam install ounit2.2.2.4 | cat
                        envVariables:
                          TERM: dumb
                          OPAMYES: "true"
                      when:
                        stageStatus: All
                      failureStrategies: []
                  - step:
                      type: Run
                      name: Run tests
                      identifier: Run_tests
                      spec:
                        connectorRef: harnessdocker
                        image: flowtype/flow-ci:linux-x86_64
                        shell: Sh
                        command: |-
                          #!/bin/bash -eo pipefail
                          .circleci/opam_init.sh
                          opam switch
                          opam exec -- make ounit-tests-ci
                        envVariables:
                          TERM: dumb
                          OPAMYES: "true"
                      when:
                        stageStatus: All
                      failureStrategies: []
              sharedPaths:
                - /flow/
        - stage:
            name: build_linux
            identifier: build_linux
            type: CI
            spec:
              cloneCodebase: true
              platform:
                os: Linux
                arch: Amd64
              runtime:
                type: Cloud
                spec: {}
              execution:
                steps:
                  - step:
                      type: Run
                      name: Create cache breaker
                      identifier: Create_cache_breaker
                      spec:
                        connectorRef: harnessnew
                        image: flowtype/flow-ci:linux-x86_64
                        shell: Sh
                        command: |-
                          ls -l .circleci/make_opam_cachebreaker.sh
                          sudo chown root .circleci/make_opam_cachebreaker.sh
                          sudo mount -o remount,exec .circleci/
                        envVariables:
                          TERM: dumb
                          OPAMYES: "true"
                  - step:
                      type: Run
                      name: Init Opam and Build
                      identifier: Init_opam
                      spec:
                        connectorRef: harnessnew
                        image: flowtype/flow-ci:linux-x86_64
                        shell: Sh
                        command: |-

                          if [ ! -f /.opam/from_cache ]; then
                            rm -rf /.opam
                            sudo opam init --bare --disable-sandboxing --no-setup --yes
                          fi

                          sudo make deps
                          eval $(opam env)

                          sudo opam init
                      when:
                        stageStatus: All
                      failureStrategies: []
                  - step:
                      type: Run
                      name: Run_5
                      identifier: Run_5
                      spec:
                        connectorRef: harnessnew
                        image: flowtype/flow-ci:linux-x86_64
                        shell: Sh
                        command: |-
                          eval $(opam env)

                          sudo opam init
                          sudo make deps-js
                      when:
                        stageStatus: All
                      failureStrategies: []
                  - step:
                      type: Run
                      name: Run_4
                      identifier: Run_4
                      spec:
                        connectorRef: harnessnew
                        image: flowtype/flow-ci:linux-x86_64
                        shell: Sh
                        command: |
                          eval $(opam env)

                          sudo opam init

                          sudo touch /.opam/from_cache

                          sudo opam exec -- make bin/flow dist/flow.zip
                          sudo mkdir -p bin/linux && cp bin/flow bin/linux/flow

                          sudo opam exec -- make -C src/parser dist/libflowparser.zip
                      when:
                        stageStatus: All
                      failureStrategies: []
                  - step:
                      type: Run
                      name: Run tests
                      identifier: Run_tests
                      spec:
                        connectorRef: harnessnew
                        image: flowtype/flow-ci:linux-x86_64
                        shell: Sh
                        command: |-
                          #!/bin/bash -eo pipefail
                          eval $(opam env)

                          sudo opam init
                          sudo ./runtests.sh bin/linux/flow | cat
                      when:
                        stageStatus: All
                      failureStrategies: []
              sharedPaths:
                - /harness/flow
  properties:
    ci:
      codebase:
        connectorRef: gitconnectordhruba
        repoName: flow
        build: <+input>
  allowStageExecutions: true
